version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $DOCKER_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker build -t $DOCKER_USERNAME/$IMAGE_REPO_NAME:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $DOCKER_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $DOCKER_USERNAME/$IMAGE_REPO_NAME:latest